services:
  - type: web
    name: safepack
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
