services:
  - type: web
    name: safepack
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: RAZORPAY_KEY_ID
        value: rzp_test_SmmzYqLPnPy6Js
      - key: RAZORPAY_KEY_SECRET
        value: QCbJBvpsKYjYtLLu7UryI8iZ
